### ISSUE TITLE
Support for QGIS expression for hotlinks

### ISSUE THREAD

**Issue by saberraz** [xcaeag/Hotlink-QGis-Plugin#1]
Currently, if you have multiple possible links listed for the hyperlinked features, you can set Field to display them.

It will be great to add HTML and expression support.

**Comment by PeterPetrik** [comment]
@xcaeag please review my PullRequst #2

**Comment by xcaeag** [comment]
Sorry for my silence, I was traveling!
Thank you for these proposals,
All these developments seem perfect, I now testing.
