### ISSUE TITLE
Hotlink fails to load: ModuleNotFoundError: No module named 'hotlink'

### ISSUE THREAD

**Issue by Julien-K** [xcaeag/Hotlink-QGis-Plugin#9]
Hello,

I get the following error message while QGis tries to load Hotlink (full message as attachment).

<<<<<<<<<<<<<<<<<
Impossible de charger l'extension 'Hotlink' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'hotlink' 
>>>>>>>>>>>>>>>>>

The module was fetched/installed through the "Extension" menu, I use QGis rel-dev 64bit:
<<<<<<<<<<<<<<<<<
Version de QGIS | 3.18.0-Zürich | Révision du code | 54a7d9cc47
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.3.0dev
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 8.1.0 | Fonctionne avec PROJ | Rel. 8.1.0, July 1st, 2021
Version de l'OS | Windows 10 (10.0) | Cette copie de QGIS dispose d'une sortie de débogage.
Extensions Python actives | changeDataSource; MemoryLayerSaver; db_manager
>>>>>>>>>>>>>>>
Same problem with QGis-dev.

Please let me know if you need additional informations to investigate this problem.

Regards,
Julien
[hotlink_fails.txt](https://github.com/xcaeag/Hotlink-QGis-Plugin/files/6082240/hotlink_fails.txt)

**Comment by Ecliptic88** [comment]
I have the same problem

**Comment by xcaeag** [comment]
I will analyze that as soon as possible !

**Comment by xcaeag** [comment]
while waiting for the new version, you can add a capital letter to the "Hotlink" plugin directory, under \ profiles \ yours \ python \ plugins

**Comment by xcaeag** [comment]
A new version is coming. 
a simple pb of case in the file ui/ui_Hotlink_chooser_dlg.py (H)

`from Hotlink.__about__ import DIR_PLUGIN_ROOT, __title__, __version__`

Thank you for this bug report.

**Comment by Ecliptic88** [comment]
Ok merci c'est noté.Merci beaucoup pour votre réactivité en tout cas.Bon week-end
Fred
    Le vendredi 5 mars 2021, 16:15:08 UTC+1, Xavier Culos <notifications@github.com> a écrit :  
 
 


A new version is coming.
a simple pb of case in the file ui/ui_Hotlink_chooser_dlg.py (H)

from Hotlink.__about__ import DIR_PLUGIN_ROOT, __title__, __version__

Thank you for this bug report.

**Comment by Julien-K** [comment]
Merci pour la correction et votre réactivité!
Julien
